### ISSUE TITLE
Can't reach you through your website: error on sending form

### ISSUE THREAD

**Issue by orl0v** [pogla/Woocommerce-Save-Product-Price-History#5]
Hello Matic!

Could you please make your WooCommerce price history script as official Wordpress plugin? I would like to pay for it.

Thank you and
greetz from Berlin

Evgeniy

**Comment by e-orlov** [comment]
Same here. Please contact me through my github email

**Comment by pogla** [comment]
Hi there. I'm making a free and premium version of this plugin with extra features. It should be ready in about 1 month or so. But it would be great if you guys can write down what features you think the plugin should have.

**Comment by e-orlov** [comment]
Hi Matic!

This sounds very cool!

It would be nice to write into DB following data:

  *   Date
  *   Product ID
  *   Category ID
  *   Price
  *   Product URL and title (maybe, not mandatory, just to save additional DB queries in the future)

My idea behind this:

Feature 1: I want to visualize price trends inside WooCommerce categories. After price history is written into DB, it would be nice to calculate (based on category) the lowest, the highest and the average price of products in the category and display it on this way:

The Chart: time-based line chart with three lines, lowest, average, highest prices.
The list: two products with lowest and highest prices

This should be displayed with shortcode in the category description.

Feature 2: I want to create category-based price alerts. Like "send me an email, if any product in this category has a price lower then the price I set"


So, the feature 1 I thought to create with this plugin<https://de.wordpress.org/plugins/wpdatatables/>.

For the feature 2 I thought to create with this plugin<https://www.tplugins.com/product/tp-price-drop-notifier-for-woocommerce-pro/>.

But, maybe, you find the idea interesting to include these features into your plugin? I have around 250€ for this.

The general goal: I plan to run a WooCommerce based site with affiliate products. There is no plugin on the market (I swear by Wordpress god:), which would have this three features: price history, charting and price drop alert, based on category. If you do it, it will be up to you to make this plugin commercial and sell it further.

Greets
Evgeniy


________________________________
Von: Matic Pogladič ***@***.***>
Gesendet: Freitag, 3. März 2023 11:17
An: pogla/Woocommerce-Save-Product-Price-History ***@***.***>
Cc: Evgeniy ***@***.***>; Comment ***@***.***>
Betreff: Re: [pogla/Woocommerce-Save-Product-Price-History] Can't reach you through your website: error on sending form (Issue #5)


Hi there. I'm making a free and premium version of this plugin with extra features. It should be ready in about 1 month or so. But it would be great if you guys can write down what features you think the plugin should have.

**Comment by e-orlov** [comment]
Hello Matic!

I'm sorry for being kinda pushy, but do you maybe already have a feedback to my feature requests/ideas?

Greets from berlin
Evgeniy

**Comment by pogla** [comment]
Hi @e-orlov

Thanks for your suggestions. Unfortunatelly I don't think these features will be implemented in the plugin. I will include these functionalities: 

1. Store price changes in the database table.
2. Display the price history chart on the single product page.
3. Price alert for a single product so people can get an email when the price drops below a certain price point.

But if you want, I can sure make a custom solution for you. Just fill in the contact form on my website https://maticpogladic.com. The form should be working now.

**Comment by e-orlov** [comment]
Would you implement charts and price alerts on category pages as commercial work?

________________________________
Von: Matic Pogladič ***@***.***>
Gesendet: Montag, 6. März 2023 14:17
An: pogla/Woocommerce-Save-Product-Price-History ***@***.***>
Cc: Evgeniy ***@***.***>; Mention ***@***.***>
Betreff: Re: [pogla/Woocommerce-Save-Product-Price-History] Can't reach you through your website: error on sending form (Issue #5)


Hi @e-orlov<https://github.com/e-orlov>

Thanks for your suggestions. Unfortunatelly I don't think these features will be implemented in the plugin. I will include these functionalities:

  1.  Store price changes in the database table.
  2.  Display the price history chart on the single product page.
  3.  Price alert for a single product so people can get an email when the price drops below a certain price point.

But if you want, I can sure make a custom solution for you. Just fill in the contact form on my website https://maticpogladic.com. The form should be working now.

**Comment by pogla** [comment]
Probably not anytime in the near future unless I see a spike in demand for these particular features. Personally, I think these features cover your use case but are not too useful otherwise.
